spring.application.name=grade-system

# PostgreSQL bağlantısı
# Kubernetes'te DB URL ConfigMap'ten okunacak.
# Kubernetes dışında çalışırken ":" sonrasındaki localhost adresi kullanılacak.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/grade_system}

# Kubernetes'te username Secret'tan okunacak.
spring.datasource.username=${DB_USERNAME:kaanerdem}

# Kubernetes'te password Secret'tan okunacak.
spring.datasource.password=${DB_PASSWORD:}

# Eskiden update kullanıyorduk: Hibernate mevcut tabloları gerektiğinde güncelliyordu.
# none ile Hibernate artık veritabanı şemasını otomatik değiştirmeyecek.
spring.jpa.hibernate.ddl-auto=none

# Spring Session tabloları gerektiğinde oluşturulsun
spring.session.jdbc.initialize-schema=always

# Hibernate'in çalıştırdığı SQL komutlarını terminalde göster
spring.jpa.show-sql=true

# Valkey bağlantısı
# Kubernetes'te VALKEY_HOST environment variable verilirse valkey-service kullanılacak.
# Local çalıştırmada verilmezse localhost kullanılacak.
spring.data.redis.host=${VALKEY_HOST:localhost}
spring.data.redis.port=${VALKEY_PORT:6379}

# Elasticsearch bağlantısı
# Kubernetes'te ELASTICSEARCH_URL environment variable üzerinden Service'e bağlanacak.
spring.elasticsearch.uris=${ELASTICSEARCH_URL:https://localhost:9200}

# Elasticsearch kullanıcı bilgileri Kubernetes ortam değişkenlerinden okunacak.
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME:elastic}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD:}

# Kubernetes'te Elasticsearch HTTPS bağlantısı için SSL bundle kullanıyoruz.
# Bu ayarlar Helm Deployment üzerinden environment variable olarak verilecek.
# spring.ssl.bundle.pem.elasticsearch.truststore.certificate=file:/app/certs/http_ca.crt
# spring.elasticsearch.restclient.ssl.bundle=elasticsearch
