spring.application.name=grade-system

# PostgreSQL bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/grade_system
spring.datasource.username=kaanerdem

# Eskiden update kullanıyorduk: Hibernate mevcut tabloları gerektiğinde güncelliyordu.
# none ile Hibernate artık veritabanı şemasını otomatik değiştirmeyecek.
spring.jpa.hibernate.ddl-auto=none

# Spring Session tabloları gerektiğinde oluşturulsun
spring.session.jdbc.initialize-schema=always

# Hibernate'in çalıştırdığı SQL komutlarını terminalde göster
spring.jpa.show-sql=true
