spring.application.name=grade-system
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.initialize-schema=always
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:gradesystem