apiVersion: v1                         # Service için kullanılan Kubernetes API sürümü
kind: Service                          # Oluşturacağımız nesne bir Service

metadata:
  name: grade-system-service           # Service'imizin adı

spec:
  type: NodePort                       # Cluster içi erişime ek olarak Node üzerinden dış erişim sağlar

  selector:
    app: grade-system                  # Bu label'a sahip Pod'lara trafik gönderir

  ports:
    - protocol: TCP
      port: 8080                       # Service'in cluster içerisindeki portu
      targetPort: 8080                 # Pod/container içerisindeki Spring Boot portu
      nodePort: 30080                  # Node üzerinden dışarı açılan port
      