create table student(
id INTEGER generated by default as identity primary key,
name VARCHAR(50) not null,
surname VARCHAR(50) not null,
email VARCHAR(100) not null,
password VARCHAR(255) not null
);

create table course (
id INTEGER generated by default as identity primary key,
name varchar(100) not null,
code varchar(10) not null unique,
teacher_name varchar(100) not null 
);

create table grade (
id integer generated by default as identity primary key,
score numeric(5,2) not null,
student_id integer not null,
course_id integer not null,

constraint fk_grade_student
	foreign key (student_id) references student(id),
	
constraint fk_grade_course
	foreign key (course_id) references course(id)
);

-- NORMAL INDEX OLUŞTURMA
create index idx_grade_student_id
on grade(student_id);

-- ÇOK KOLONLU INDEX OLUŞTURMA
create index idx_grade_student_course
on grade(student_id, course_id);

-- VERİLERİ EKLEME (INSERT)
insert into student (name,surname,email,password)
values
	('Kaan', 'Erdem', 'kaan@example.com', 'password_1'),
	('Eda', 'Esertaş', 'eda@example.com', 'password_2'),
	('Selin', 'Uysal', 'selin@example.com', 'password_3');

select * from student;

select * from course;

insert into course(name,code,teacher_name)
values 
	('Database Management', 'DB101', 'AHMET YILMAZ'),
	('Software Testing', 'ST101', 'AYŞE KAYA'),
	('Web Programming', 'WEB101', 'ALİ DEMİR');

select * from course;

insert into grade (score,student_id,course_id)
values 
	(85.00, 1, 1),
	(80.00, 1, 2),
	(100.00, 2, 1),
	(50.50, 2, 3),
	(78.00, 3, 2);

select * from grade;

-- INNER JOIN: ÖĞRENCİ, DERS VE NOT BİLGİLERİNİ BİRLEŞTİRME
select 
	student.name as "Student Name",
	student.surname as "Student Surname",
	course.name as "Course Name",
	grade.score as "Score"
from grade
inner join student on grade.student_id = grade.student.id
inner join course on grade.course_id = grade.course.id;

-- NOTU OLMAYAN ÖĞRENCİ EKLEME (LEFT OUTER JOIN TESTİ İÇİN)
insert into student (name,surname,email,password)
values ('Mert', 'Yılmaz', 'mert@example.com', 'password_4');

-- LEFT OUTER JOIN: NOTU OLMAYAN ÖĞRENCİLERİ DE LİSTELEME
select 
	student.name,
	course.name,
	grade.score
from student 
left outer join grade on student.id = grade.student_id
left outer join course on grade.course_id = course.id;

-- GROUP BY: ÖĞRENCİLERİN NOT ORTALAMALARINI HESAPLAMA
select 
	student.name as "Student Name",
	avg(grade.score) as "Average Score"
from student
inner join grade on student.id = student_id
group by student.id, student.name;

-- GROUP BY: DERSLERİN NOT ORTALAMALARINI HESAPLAMA
select
	course.name as "Course Name",
	avg(grade.score) as "Average Score"
from course
inner join grade on course.id = course_id
group by course.id, course.name;

-- HAVING: ORTALAMASI 78'DEN YÜKSEK DERSLERİ LİSTELEME
select 
	course.name as "Course Name",
	avg(grade.score) as "Average Score"
from course
inner join grade on course.id = course_id
group by course.id, course.name 
having AVG(grade.score)>78;

-- UNION: ÖĞRENCİ VE ÖĞRETMEN İSİMLERİNİ TEK LİSTEDE BİRLEŞTİRME
select name as "People"
from student
union 
select teacher_name as "People"
from course;

-- WITH (CTE): DERS ORTALAMALARINI GEÇİCİ SONUÇ OLARAK OLUŞTURMA
-- VE ORTALAMASI 80'DEN YÜKSEK DERSLERİ LİSTELEME
with course_averages as(
	select 
		course.id,
		course.name,
		avg(grade.score) as "Average Score"
	from course
	inner join grade on course.id = grade.course_id
	group by course.id, course.name
)
select * 
from course_averages
where "Average Score" > 80;

--ALTER TABLE student = var olan student tablosunu değiştir
ALTER TABLE student
ADD CONSTRAINT uq_student_email UNIQUE (email);
/* ADD CONSTRAINT = yeni bir kural ekle 
uq_student_email = kurala bizim verdiğimiz açıklayıcı isim
UNIQUE(email) = aynı email'in iki kere kullanılmasını engelle.*/

-- CHECK CONSTRAINT: NOT DEĞERİNİN 0-100 ARASINDA OLMASINI SAĞLAMA
alter table grade
add constraint chk_grade_score
check (score BETWEEN 0 AND 100);

-- ORDER BY: NOTLARI YÜKSEKTEN DÜŞÜĞE SIRALAMA
select
    id,
    score
from grade
order by score desc;

-- ORDER BY: NOTLARI DÜŞÜKTEN YÜKSEĞE SIRALAMA
select
    id,
    score
from grade
order by score asc;

-- LIMIT: EN YÜKSEK 3 NOTU GETİRME
select
    id,
    score
from grade
order by score desc
limit 3;

-- COUNT: TOPLAM ÖĞRENCİ SAYISINI BULMA
select count(*) AS "Student Count"
from student;

-- MIN VE MAX: EN DÜŞÜK VE EN YÜKSEK NOTU BULMA
select
    min(score) AS "Minimum Score",
    max(score) AS "Maximum Score",
    avg(score) as "Average Score"
FROM grade;










