apiVersion: v1
kind: Secret
metadata:
  name: grade-system-db-secret
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}

  # JWT tokenlarını imzalamak için kullanılan gizli anahtar.
  JWT_SECRET: {{ .Values.jwt.secret | quote }}